[package]
name = "ytps"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6"
tokio = { version = "1.37", features = ["full"] }
tokio-util = "0.7"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
dirs = "5.0"

